# Generated by Django 2.0.9 on 2021-08-05 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(related_name='circle_members', through='circles.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
